- name: directory
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ wallpapers_dir }}"

- name: copy
  win_copy:
    src: "{{ item }}"
    dest: "{{ wallpapers_dir }}/{{ item }}"
  with_items:
    - "{{ wallpapers_file_list }}"

# Local Variables:
# indent-tabs-mode: nil
# End:
