windows_packages_download_local_dir: "{{ playbook_dir }}/files"
windows_packages_download_windows_dir: "{{ ansible_user_dir }}\\Documents\\Packages"

windows_packages_package_url_list:
  - name: putty-64bit-0.73-installer.msi
    url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.73-installer.msi
    cksum: 31d001504b56e47d7e90b39a6fde6acf949e8c59d4717abac35eef0b932f89d7
    cksum_type: sha256

# Local Variables:
# indent-tabs-mode: nil
# End:
