- name: setup check
  win_stat:
    path: C:\Chocolatey\lib
  register: chocolatey_packages_chocolatey_lib

- name: setup
  when: not(chocolatey_packages_chocolatey_lib.stat.exists and chocolatey_packages_chocolatey_lib.stat.isdir)
  block:
    - name: package provider
      win_shell: "Get-PackageProvider -Name {{ item }} -ForceBootstrap"
      with_items:
        - NuGet
        - Chocolatey

    - name: chocolatey
      win_shell: "Install-Package -Name {{ item }} -Force -ProviderName chocolatey"
      with_items:
        - chocolatey

- name: packages
  win_chocolatey:
    name: "{{ item.name }}"
    params: "{{ item.params | default() }}"
    timeout: "{{ item.timeout | default(2700) }}"
    state: present
  with_items:
    - "{{ chocolatey_packages_chocolatey_package_list }}"

- name: install packages
  win_shell: "Install-Package -Name {{ item }} -ProviderName chocolatey"
  with_items:
    - "{{ chocolatey_packages_install_package_list }}"

# Local Variables:
# indent-tabs-mode: nil
# End:
