- name: package provider
  win_command: "powershell Get-PackageProvider -Name {{ item }}"
  with_items:
    - NuGet
    - Chocolatey

- name: packages
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ chocolatey_packages_chocolatey_package_list }}"

# Local Variables:
# indent-tabs-mode: nil
# End:
