- name: virtual store directory
  win_file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ teraterm_settings_virtual_store_dir }}"
    - "{{ teraterm_settings_virtual_store_dir }}\\theme"

- name: initial setting file
  win_copy:
    src: "{{ teraterm_settings_program_files_dir }}\\{{ item }}"
    dest: "{{ teraterm_settings_virtual_store_dir }}\\{{ item }}"
    force: no
    remote_src: yes
  with_items:
    - TERATERM.INI
    - theme\ImageFile.INI

- name: TERATERM.INI
  win_lineinfile:
    path: "{{ teraterm_settings_virtual_store_dir }}\\TERATERM.INI"
    insertafter: "^\\[{{ item.section | regex_escape }}\\]$"
    regexp: "^{{ item.option | regex_escape }}\\s*="
    line: "{{ item.option }}={{ item.value }}"
    encoding: shift_jis
    backup: yes
  with_items:
    - "{{ teraterm_settings_item_list }}"

- name: ImageFile.INI
  win_lineinfile:
    path: "{{ teraterm_settings_virtual_store_dir }}\\theme\\ImageFile.INI"
    insertafter: "^\\[{{ item.section | regex_escape }}\\]$"
    regexp: "^{{ item.option | regex_escape }}\\s*="
    line: "{{ item.option }}={{ item.value }}"
    encoding: shift_jis
    backup: yes
  with_items:
    - "{{ teraterm_settings_image_list }}"

# Local Variables:
# indent-tabs-mode: nil
# End:
