- name: WSL directory exits?
  delegate_to: localhost
  stat:
    path: /mnt/c/Windows
  register: windir

- name: WSL facts
  when: windir.stat.exists and windir.stat.isdir
  block:
    - name: WSL path
      delegate_to: localhost
      command: "wslpath -u {{ ansible_user_dir | quote }}"
      register: wslpath
    - name: WSL user directory
      set_fact:
        wsl_user_dir: "{{ wslpath.stdout }}"
    - name: overwrite windows_packages_download_local_dir
      set_fact:
        windows_packages_download_local_dir: "{{ wsl_user_dir }}/Documents/Packages"
    - name: overwrite transpwnds_download_local_dir
      set_fact:
        transpwnds_download_local_dir: "{{ wsl_user_dir }}/Documents/TranspWnds"
    - name: overwrite manual_installers_download_local_dir
      set_fact:
        manual_installers_download_local_dir: "{{ wsl_user_dir }}/Documents/Installers"

# Local Variables:
# indent-tabs-mode: nil
# End:
